---
title: "Case Study 1"
author: "Karen, Samuel, Laurence"
date: "February 8, 2019"
output: 
        html_document:
        keep_md: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- install packages -->
```{r echo=FALSE, include=FALSE}

   install.packages('dplyr', repos="http://cran.us.r-project.org")
   install.packages('knitr', repos="http://cran.us.r-project.org")
   install.packages('rvest', repos="http://cran.us.r-project.org")
   install.packages('ggplot2', repos="http://cran.us.r-project.org")
  install.packages('psych', repos="http://cran.us.r-project.org")
   install.packages('kableExtra')

```
      **libraries used**
      
        library(dplyr)
        library(knitr)
        library(rvest)
        library(ggplot2)
        library(psych)
      


## Load dataset into R.



```{r ReadFile}
#setwd("C:/SMU/doing_data_science/CaseStudy1/CaseStudy1")
#Read in the beers.csv and set to data frame
Beers <- read.csv("Beers.csv", header = TRUE, sep = ",")


#Read in the Breweries.csv and set to data frame
Breweries <- read.csv("Breweries.csv", header = TRUE, sep = ",")



```

##  Merge document and show top and bottom 6 rows


```{r merging}
#add equivalent name to Beers data frame for merge
Beers$Brew_ID <- Beers$Brewery_id


#Merge the data frames
dataset_merge <- merge(Breweries,Beers, by="Brew_ID",all=TRUE)

#Top 6 observations from merged file
Top6 <- head(dataset_merge,6)
Top6

#Bottome 6 observations from merged file
Bottom6 <- tail(dataset_merge)
Bottom6

```
## Rename columns to be more readable

```{r rename columns}
#Rename columns 
names(dataset_merge) <- c("Brew_ID","Company_Name","City","State","Beer_Name","Beer_ID","ABV","IBU", "Brew_ID","Beer_Style","OUnces")
Top10 <- head(dataset_merge)
Top10

```
## Show NA
```{r showNA}
#Get NA count from each column

ExamineNA <- function(column){
    
                  testNA <- sum(is.na(dataset_merge[column]))
                  
                  print (column)
                  print (testNA)
                }
  
  
 
for (x in names(dataset_merge)){ ExamineNA(x)}

```

## Breweries per state

```{r BreweriesPerState}
#find number of breweries in state
library(plyr)

BreweryState <- count(dataset_merge,"State")
BreweryState

```


```{r statesize}

#Plot of Breweries per State
library(ggplot2)

b1 <- ggplot(BreweryState, aes(x=reorder(BreweryState$State,-BreweryState$freq), y=BreweryState$freq, fill=BreweryState$State)) +
  
geom_bar(stat="identity") + labs(title ="Breweries in States", x= "States", y="Number of Breweries", fill="States") + theme(text = element_text(size=7),axis.text.x = element_text(angle=90, hjust=1))

b1

```

The median alcohol content and international bitterness units were calculated for each state and are shown in the tables and barplots below.    

```{r medians}
#Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare. 
library(psych)
library(kableExtra)
ABV_St <- describeBy(dataset_merge$ABV, dataset_merge$State, mat=T)
colnames(ABV_St)[colnames(ABV_St)=="group1"] <- "State"
IBU_St <- describeBy(dataset_merge$IBU, dataset_merge$State, mat=T)
colnames(IBU_St)[colnames(IBU_St)=="group1"] <- "State"
head(IBU_St)
ABV_St[,c(2,7)] %>%
  kable() %>%
  kable_styling()
IBU_St[,c(2,7)] %>%
  kable() %>%
  kable_styling()
```        


```{r Final}
#bar plot of Median Alcohol by volumne
ABV_plot <- ggplot(ABV_St, aes(x=ABV_St$State, y=ABV_St$median, fill=ABV_St$State)) +
  geom_bar(stat="identity") + labs(title ="Median Alcohol by Volume in States", x= "States", y="ABV", fill="States") + theme(text = element_text(size=9),axis.text.x = element_text(angle=90, hjust=1))

ABV_plot


#bar plot of Median IBU in states
IBU_plot <- ggplot(IBU_St, aes(x=IBU_St$State, y=IBU_St$median, fill=IBU_St$State)) +
  geom_bar(stat="identity") + labs(title ="Median Intl Bitterness in States", x= "States", y="IBU", fill="States") + theme(text = element_text(size=9),axis.text.x = element_text(angle=90, hjust=1))	

IBU_plot
```    

